project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sam-trg
      - icon: instagram
        href: https://instagram.com/vegansamburger
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css



